### ISSUE TITLE
Exception when calling DeviceInventory.get_all

### ISSUE THREAD

**Issue by Tom-Tom-Bo** [SoftwareAG/cumulocity-python-api#4]
Function _DeviceInventory.get_all()_ delegates its call to its parent, _Inventory.get_all()_, which in turn calls _self.select()_. That results in a parameter missmatch as self refers to an instance of _DeviceInventory_ while the function parameters match with _Inventory.select()_

Replacing line 784 in module/inventory.py with
    `return [ x for x in self.select( type = type, name = name, page_size = page_size ) ]`
 resolved the issue for me

**Comment by chisou** [comment]
Good find!
Fixed for next release.
