### ISSUE TITLE
Notification 2 API SSL Error 

### ISSUE THREAD

**Issue by simeonthefirst** [SoftwareAG/cumulocity-python-api#43]
`c8y.notification2_tokens.build_websocket_uri(token) ` always returns `wss://...` instead of `ws://` what is needed when running it inside of a cumulocity hosted microservice. What i do now is using my own Listener and creating the uri like this: `f"{c8y.base_url.replace('http','ws')}/notification2/consumer/?token={token}"`

**Comment by chisou** [comment]
This is fixed with [version 1.8.2](https://github.com/SoftwareAG/cumulocity-python-api/releases/tag/v1.8.2).
